% '-LC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\lib\x64'

mexcuda -dynamic -DUSE_DOUBLE -v ...
    '-LC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\lib\x64' ...
    -I\. mexSolveModelGivenParms.cu liquidity_mex_defs.cu normaldist_mex.cu ...
    tauchen_mex.cu liquidity_vfi_mex.cu

% mexcuda -dynamic -DUSE_SINGLE -v ...
%     '-LC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\lib\x64' ...
%     -I\. mexSolveModelGivenParms.cu liquidity_mex_defs.cu normaldist_mex.cu ...
%     tauchen_mex.cu liquidity_vfi_mex.cu